#!/bin/bash
# Generic bash options which I always use for safety. Not all may be needed for this particular script.
set -o nounset
set -o pipefail
set -o errexit
set -o errtrace
trap 'echo "Error at line $LINENO, exit code is $?" >&2' ERR
shopt -s nullglob
shopt -s failglob

if [ $# -ne 2 ] ; then
	echo "This is a wrapper around kdesu to fix its lack of properly setting all environment variables and initializing all of KDE." >&2
	echo "" >&2
	echo "Syntax: $0 USER COMMAND" >&2
	echo "Passing arguments to the COMMAND is NOT supported!" >&2
	exit 1
fi

user="$1"
program="$2"

dbus_running() {
	local dbus_env="$1"
	[ -z "$dbus_env" ] && exit 1
	
	[ -f "$dbus_env" ] &&
	source "$dbus_env" &&
	ps --pid "$DBUS_SESSION_BUS_PID" > /dev/null
}

# XDG_RUNTIME_DIR is supposed to persist while the user stays logged in,
# but needs not persist across machine restarts. See $ man pam_systemd.
# Thus a bare mktemp will not be sufficient, we must store the dir.
set_xdg_runtime_dir_from_file() {
	local file="$1"
	[ -z "$file" ] && exit 1
	
	local dir
	if [ -f "$file" ] ; then
		dir=$(<"$file")
	fi
	
	if [ -z "$dir" ] || ! [ -d "$dir" ] ; then
		if ! dir="$(mktemp --directory)" ; then
			return 1
		fi
		cat <<< "$dir" > "$file" # echo isn't safe with arbitrary strings
	fi
	
	XDG_RUNTIME_DIR="$dir"
}

if [ "$(whoami)" != "$user" ] ; then
	# See $ man kdesu
	kdesu="$(kde4-config --path libexec)"kdesu
	
	# -n not only to avoid saving passwords but also to ensure the kdesu daemon isn't started:
	# This script intends to ensure that no processes spawned by it keep running once the launched program has exited.
	#
	# Reason for the user check in the passed bash script even though we already checked here:
	# If the user presses the "ignore" button when being asked for a password kdesu will run the program as the current user.
	# Thus we must check if we are the target user before running ourselves to avoid a fork bomb.
	"$kdesu" -n -u "$user" -t -c "bash -xc 'realuser=\$(whoami) && [ \"\$realuser\" = \"$user\" ] && \"$0\" \"$user\" \"$program\"'"
else
	# For easy debugging
	set -x
	
	# Prevent e.g. save dialogs in the GUI from starting at the inaccessible
	# homedir of the calling user.
	cd "$HOME"
	
	# We need a directory which persists across multiple executions to
	# ensure we can re-use existing dbus-daemon instances.
	my_dir="$HOME/.cache/kdesu-fixup"
	mkdir --parents "$my_dir"
	chmod 0700 "$my_dir"
	
	# The following environment variables which kdesu doesn't deal with were obtained by:
	# 	set | fgrep UID_OF_CALLING_USER
	# 	set | fgrep NAME_OF_CALLING_USER
	# where the "calling user" is the user which called kdesu. So these variables should be adjusted to refer to $user's stuff instead.
	# Some were also determined by watching output of kontact for errors.
	
	set_xdg_runtime_dir_from_file "$my_dir/xdg_runtime_dir"
	export XDG_RUNTIME_DIR
	export GS_LIB="$HOME/.fonts"
	export KDE_SESSION_UID="$UID"
	export GPG_AGENT_INFO=
	export PAM_KWALLET_LOGIN=
	export PAM_KWALLET5_LOGIN=
	# FIXME: Is $PATH valid or is the one of the calling user inherited?
	
	# FIXME: kontact will crash on new user acccounts due to lack of initializing the system configuration cache
	# Run the following as the target user before launching the program:
	#	kbuildsyscoca4 # Use --incremental ?
	#	kbuildsyscoca5 # Use --incremental ?
	
	# TODO: Firefox once complained about not being able to create a dconf
	# dir in some /tmp dir. Unable to reproduce it unfortunately.
	# Is it necessary to create it? And is it really in the XDG_RUNTIME_DIR?
	#	mkdir "$(XDG_RUNTIME_DIR)/dconf"
	
	# E.g. chromium-browser will fail to launch dbus on its own and print
	# errors so we start it manually.
	# Fortunately dbus offers a tool "dbus-launch" whose manpage sounds
	# like it is intended to start dbus for the sole purpose of using
	# a program with it, just what we want to do.
	dbus_env="$my_dir/dbus-environment"
	if ! dbus_running "$dbus_env" ; then
		dbus-launch --exit-with-x11 --sh-syntax > "$dbus_env"
	fi
	source "$dbus_env"
	
	# FIXME: $ man dbus-launch says:
	# "If you run dbus-launch myapp (with any other options), dbus-daemon
	# will not exit when myapp terminates: this is because myapp is assumed
	# to be part of a larger session, rather than a session in its own right."
	# -> How to tell dbus to shutdown when no more programs are using it?
	# EDIT: The $dbus_env file contains DBUS_SESSION_BUS_PID, we might be
	# able to kill it by killing that process.
	
	# FIXME: chromium-browser startup is slow due to a timeout:
	# 	Failed to call method: org.freedesktop.Notifications.GetCapabilities:
	# 	object_path= /org/freedesktop/Notifications:
	# 	org.freedesktop.DBus.Error.NoReply: Did not receive a reply.[...]
	# This possibly is because there is no notification widget running in the
	# target user: https://bbs.archlinux.org/viewtopic.php?id=236020
	
	"$program"
fi
